

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#

extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages', 
    'numpydoc',  
    'nbsphinx', 'IPython.sphinxext.ipython_console_highlighting',
    'myst_parser',
    'sphinx_gallery.gen_gallery']


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'PTM-POSE'
copyright = '2024, Naegle Lab'
author = 'Naegle Lab'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0'
# The full version, including alpha/beta/rc tags.
release = '1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '**.ipynb_checkpoints', '.gitignore', '.gitattributes', '.zip','.py']

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'




# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.


html_theme = 'sphinx_book_theme'
#html_theme = 'sphinx_rtd_theme'

#dotted

html_theme_options = {
    'repository_url':'https://github.com/NaegleLab/PTM-POSE',
    'use_repository_button': True
}

html_title = 'PTM-POSE'


sphinx_gallery_conf = {
     'examples_dirs': './gallery',   # path to your example scripts
     'gallery_dirs': 'gallery_output',  # path to where to save gallery generated output
}

