{% set name = "ptm-pose" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptm_pose-{{ version }}.tar.gz
  sha256: c62d4f3ace883a47936ac31b6f04bca528509664cbb11638ca28b2b2d58c456b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pandas ==2.2.*
    - numpy ==1.26.*
    - scipy ==1.13.*
    - biopython ==1.78.*
    - tqdm ==4.66.*
    - networkx ==3.3
    - xlrd
    - matplotlib-base
    - seaborn
    - requests

test:
  imports:
    - ptm_pose

about:
  home: https://github.com/NaegleLab/PTM-POSE/tree/main
  summary: 'PTM-POSE: PTM Projection onto Splice Events'
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srcrowl
